### PR TITLE
Bump to version 0.6.1 : screen dimming implemented

### PR DESCRIPTION
**Pull request by Jkillelea**
Method takes a boolean, true = screen dim. Implementation pretty much identical to the Adafruit C++ and Python libraries

### CODE REVIEW

**Comment by Jkillelea** [comment]
Looks like the failing builds are due to changes within  codeclimate-test-reporter. I've tested this code in IRB and it does indeed change the brightness of my OLED display.

**Comment by viacommits** [comment]
> Looks like the failing builds are due to changes within codeclimate-test-reporter.

Yes.  That should be fixed on the latest master.  Please rebase and undo changes to remove image and imagemagick.  Thanks for all your contributions!

**Comment by Jkillelea** [comment]
Done. Latest commit on my fork requires rmagick and implements dimming functionality. Submitted as a new pull request.

**Comment by Jkillelea** [comment]
Done. Latest commit on my fork has

**Pull request closed without merging**
